name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
          
      - name: Cache NPM and Cypress 
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          
      - run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/tests/*.js
          browser: firefox
